### ISSUE TITLE
Don't append new output to existing file

### ISSUE THREAD

**Issue by moekappels** [internet-sicherheit/ethereum-cache-creator#30] opened 2020-05-18 08:18 UTC
The current implementation will add a new JSON array object into the existing file, if file already existing. This leads to broken JSON and therefore can't be a desired behavior.

There are two alternatives:

    Append to existing JSON array
    Use a more complex JSON object as the file root and record each run as a new session
    Just override the file

1 sounds wrong and leads to semantically wrong data, so for the sake of simplicity, I'd suggest using solution 3.

**Comment by kiview** [comment] 2020-05-27 09:06
Duplicate of #28

**Closed by kiview** 2020-05-27 09:06 UTC
