### ISSUE TITLE
Get data out of ethereum blockchain using web3j

### ISSUE THREAD

**Issue by beeshot** [internet-sicherheit/ethereum-cache-creator#4] opened 2020-04-27 10:35 UTC

**Comment by moekappels** [comment] 2020-04-28 05:27
got a weird error with nonce:
Caused by: org.web3j.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
        at org.web3j.utils.Numeric.decodeQuantity(Numeric.java:43)
        at org.web3j.protocol.core.methods.response.EthBlock$Block.getNonce(EthBlock.java:162)

**Comment by kiview** [comment] 2020-04-28 06:36
How is this error related to this issue? A bit more context please, or create a new bug issue if this is a reproducible bug that needs fixing.

**Comment by moekappels** [comment] 2020-05-07 09:06
i suspect i get this error cus even thou nonce exists in ethereum in general it is not used in bloxberg.

**Comment by kiview** [comment] 2020-05-07 09:21
Yes, because `nonce` is AFAIK part of PoW algorithms, which are not used in bloxberg.
This issue itself seems closed by the code in https://github.com/internet-sicherheit/ethereum-cache-creator/blob/master/src/main/java/de/internetsicherheit/brl/bloxberg/cache/ethereum/BloxbergClient.java#L42-L47

I, therefore, close this issue. Feel free to open more specific issues for this big or missing data.

**Closed** 2020-05-07 09:22 UTC
